[build]
  command = """
    curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable &&
    source $HOME/.cargo/env &&
    cargo install wasm-pack &&
    wasm-pack build --target web --out-dir app/pkg &&
    cd app &&
    pnpm install &&
    pnpm build
  """
  publish = "www-dist"

[build.environment]
  RUSTUP_TOOLCHAIN = "stable"
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200