//! **Old logs still open.** Real v7 and v8 op-log bytes, off real builds, run
//! through the real resume entry point under today's engine.
//!
//! This is the green twin of `oplog_v8_text_settings_replay.rs`. That file
//! proves the ADR-060 repair works; this one proves the repair costs nothing
//! to the logs already on users' disks — and it keeps proving it after the
//! next format step, which is the reason it is permanent rather than a
//! one-session check.
//!
//! ## What it would have caught
//!
//! `OP_FORMAT_VERSION` has collided on parallel branches TWICE (v6 and v8).
//! The shape of that accident is always the same: a branch writes bytes under
//! a number another branch already shipped, and nothing in the suite reads a
//! byte that a previous release actually wrote. Every other replay test in
//! this crate builds its input by calling `encode_op` — which stamps the
//! CURRENT version, so it agrees with itself no matter what the number is.
//! These two fixtures cannot: their version bytes are 7 and 8 and they were
//! frozen on 2026-09-20 from builds that are already in the release history.
//!
//! `decode_op` accepts `2..=OP_FORMAT_VERSION`. A future step that is NOT
//! append-only has to narrow that range deliberately, and the moment it does,
//! these tests go red and name the documents it is about to orphan. That is
//! the conversation, held before the deploy instead of after it.
//!
//! ## Provenance
//!
//! | Fixture | Version in the BYTES | Built by |
//! |---|---|---|
//! | `v8-text-font-wrap-shape.frames.bin` | 8 | edit.imagehorse.app, commit 34dd0d9 |
//! | `v7-text-wrap-shape.frames.bin` | 7 | local production build of 6a3de6be |
//!
//! Sidecar JSON (op list, chunk boundaries, sha256) sits next to each one;
//! `tests/fixtures/oplog/README.md` has the capture procedure. The version was
//! read out of the frame bytes, never from the filename — the first v7 attempt
//! lost a port race and came back v8, which is the only reason that discipline
//! is worth stating.

use stamp_tool::ops::OP_FORMAT_VERSION;
use stamp_tool::ImageHorseTool;

const KEYFRAME_PNG: &[u8] = include_bytes!("fixtures/oplog/base-keyframe-276x276.png");

const V7_FRAMES: &[u8] = include_bytes!("fixtures/oplog/v7-text-wrap-shape.frames.bin");
const V7_ANNOTATIONS: &[u8] = include_bytes!("fixtures/oplog/base-annotations.v7.bin");
const V7_OP_COUNT: u32 = 5;

const V8_FRAMES: &[u8] = include_bytes!("fixtures/oplog/v8-text-font-wrap-shape.frames.bin");
const V8_ANNOTATIONS: &[u8] = include_bytes!("fixtures/oplog/base-annotations.v8.bin");
const V8_OP_COUNT: u32 = 6;

/// Pull `"<key>":<value up to the next comma>` out of the annotations JSON.
/// The dependency-free reader `tests/oplog_v3_resume.rs` uses, for the same
/// reason: the crate has no `serde_json` dev-dependency.
fn field(json: &str, key: &str) -> String {
    let at = json
        .find(key)
        .unwrap_or_else(|| panic!("{key} missing from {json}"));
    let rest = &json[at + key.len()..];
    let end = rest.find(',').unwrap_or(rest.len());
    rest[..end].to_string()
}

/// The format-version byte of the FIRST frame. Framing is
/// `[u32 LE frame length][format-version u8][postcard(Op)]`, so it is byte 4.
fn first_frame_version(frames: &[u8]) -> u8 {
    assert!(frames.len() > 4, "fixture is too short to hold one frame");
    frames[4]
}

fn resume(annotations: &[u8], frames: &[u8], cursor: u32) -> ImageHorseTool {
    let mut t = ImageHorseTool::new(276, 276);
    assert!(
        t.oplog_restore_png(KEYFRAME_PNG, annotations, frames, cursor),
        "a log a shipped build wrote must still restore at cursor {cursor}"
    );
    t
}

// ── The version bytes are what they claim, and the reader still takes them ──

#[test]
fn the_fixtures_really_carry_the_old_version_bytes() {
    // If this goes red the fixtures were regenerated by a current build and
    // every other test in this file has quietly stopped testing anything.
    assert_eq!(first_frame_version(V7_FRAMES), 7, "v7 frames");
    assert_eq!(first_frame_version(V8_FRAMES), 8, "v8 frames");
    assert_eq!(V7_ANNOTATIONS[0], 7, "v7 base annotation blob");
    assert_eq!(V8_ANNOTATIONS[0], 8, "v8 base annotation blob");
}

#[test]
fn the_accepted_version_range_still_covers_both_fixtures() {
    // `decode_op` accepts 2..=OP_FORMAT_VERSION. Bumping the constant keeps
    // this green; NARROWING the range (a step that is not append-only) turns
    // it red, and that is the point — the red names the logs being orphaned.
    for v in [
        first_frame_version(V7_FRAMES),
        first_frame_version(V8_FRAMES),
    ] {
        assert!(
            (2..=OP_FORMAT_VERSION).contains(&v),
            "a released build wrote version {v}; this engine accepts 2..={OP_FORMAT_VERSION}"
        );
    }
}

// ── v8: the log that ships today ────────────────────────────────────────────

#[test]
fn a_v8_log_resumes_with_its_face_and_its_box() {
    let t = resume(V8_ANNOTATIONS, V8_FRAMES, V8_OP_COUNT);
    let j = t.get_text_annotations();
    assert!(
        j.contains("\"text\":\"wrap me across several lines please\""),
        "the text came back: {j}"
    );
    assert_eq!(
        field(&j, "\"font_id\":"),
        "\"liberation-serif\"",
        "the face the user picked: {j}"
    );
    assert_eq!(
        field(&j, "\"wrap_width\":"),
        "299",
        "the box the user dragged: {j}"
    );
}

// ── v7: a log written before the font selector existed ──────────────────────

#[test]
fn a_v7_log_resumes_with_the_box_its_user_dragged() {
    // MEASURED, not reasoned. Under v8.80 this same fixture came back
    // `wrap_width: 0` with a 359 px single-line tile; under the ADR-060 merge
    // it comes back 338 with a 289 px wrapped one. v7 predates `TextFont`
    // entirely, so its log is TextAdd / TextWrap / TextEdit / ShapeAdd /
    // ShapeSloppiness — the same `TextEdit` erasure, one version earlier, and
    // repaired by the same rule with no migration step and no rewrite.
    let t = resume(V7_ANNOTATIONS, V7_FRAMES, V7_OP_COUNT);
    let j = t.get_text_annotations();
    assert_eq!(
        field(&j, "\"wrap_width\":"),
        "338",
        "the dragged width survives a v7 log too: {j}"
    );
}

#[test]
fn a_v7_log_does_not_acquire_a_typeface_it_never_had() {
    // The other half of "old logs still open": nothing is invented either.
    // `font_id` is `""` — the embedded Liberation Sans, which is the only face
    // that existed when these bytes were written.
    let t = resume(V7_ANNOTATIONS, V7_FRAMES, V7_OP_COUNT);
    let j = t.get_text_annotations();
    assert_eq!(field(&j, "\"font_id\":"), "\"\"", "no face invented: {j}");
}

#[test]
fn both_logs_keep_the_shape_setting_that_was_already_working() {
    // The control that spans both versions: `sloppiness` rides `ShapeSloppiness`
    // and was never lost, so a red row above means the text path and not a
    // broken fixture, a bad keyframe or a mis-built engine.
    for (name, ann, frames, cursor) in [
        ("v7", V7_ANNOTATIONS, V7_FRAMES, V7_OP_COUNT),
        ("v8", V8_ANNOTATIONS, V8_FRAMES, V8_OP_COUNT),
    ] {
        let t = resume(ann, frames, cursor);
        let j = t.get_shape_annotations();
        assert_eq!(field(&j, "\"sloppiness\":"), "50", "{name} shape: {j}");
    }
}

// ── The archive contract: the captured JSON is still the engine's JSON ───────

const ENGINE_TEXT_FIXTURE: &str = include_str!("fixtures/oplog/v8-engine-text-annotations.json");

/// Key names in a JSON object: every `"ident":` in the string.
///
/// Dependency-free on purpose — the crate has no `serde_json` dev-dependency,
/// and `tests/oplog_v3_resume.rs` already reads these fixtures the same way.
/// It would mis-read a key containing an escaped quote; `annotations_to_json`
/// writes a fixed field list, so none does.
fn json_keys(json: &str) -> Vec<String> {
    keys_delimited(json, "\"")
}

/// The same, for JSON that has been EMBEDDED in another JSON string, where the
/// quotes arrive as `\"`. That escaping is what makes this precise: the outer
/// sidecar's own keys (`note`, `producedBy`, …) use bare quotes and are
/// therefore invisible here, so the result is exactly the captured annotation's
/// key set.
fn escaped_json_keys(raw: &str) -> Vec<String> {
    keys_delimited(raw, "\\\"")
}

fn keys_delimited(raw: &str, quote: &str) -> Vec<String> {
    let flat = raw.replace(quote, "\u{1}");
    let mut keys: Vec<String> = Vec::new();
    let mut rest = flat.as_str();
    while let Some(start) = rest.find('\u{1}') {
        let after = &rest[start + 1..];
        let Some(end) = after.find('\u{1}') else {
            break;
        };
        let token = &after[..end];
        let tail = &after[end + 1..];
        if tail.starts_with(':') && !token.is_empty() {
            keys.push(token.to_string());
        }
        rest = tail;
    }
    keys.sort();
    keys.dedup();
    keys
}

#[test]
fn the_captured_engine_json_still_carries_every_key_the_engine_emits() {
    // ⚠️ THE LOOP-CLOSER. `app/src/lib/editPersistence.stripDrift.test.ts`
    // derives "what the archive must carry" from
    // `fixtures/oplog/v8-engine-text-annotations.json` rather than from a type
    // the app declares — that is what makes it able to see a dropped field at
    // all. A captured fixture goes stale, though, and a stale fixture is blind
    // for the same reason the old guard was.
    //
    // So this compares the fixture against a LIVE `get_text_annotations()`.
    // Add a field to `annotations_to_json` and this goes red first, before the
    // app has any chance to silently not persist it. The fix is to recapture
    // the fixture, then teach `PersistedAnnotation` and `restoreLayerStack`
    // about the field — in that order.
    let live = resume(V8_ANNOTATIONS, V8_FRAMES, V8_OP_COUNT).get_text_annotations();
    assert_eq!(
        json_keys(&live),
        escaped_json_keys(ENGINE_TEXT_FIXTURE),
        "the engine's text JSON and the captured fixture have drifted — \
         recapture tests/fixtures/oplog/v8-engine-text-annotations.json, then \
         teach PersistedAnnotation and restoreLayerStack the new field"
    );
}

#[test]
fn control_the_key_reader_can_actually_tell_two_key_sets_apart() {
    // A comparison that cannot fail proves nothing. Both readers find the same
    // keys in the same document written two ways, and both notice a missing
    // one.
    let plain = r#"[{"id":1,"font_id":"liberation-serif","wrap_width":168}]"#;
    let embedded =
        r#"{"engineJson":"[{\"id\":1,\"font_id\":\"liberation-serif\",\"wrap_width\":168}]"}"#;
    assert_eq!(json_keys(plain), escaped_json_keys(embedded));
    assert_eq!(json_keys(plain), vec!["font_id", "id", "wrap_width"]);
    assert_ne!(
        json_keys(plain),
        json_keys(r#"[{"id":1,"font_id":"liberation-serif"}]"#),
        "a dropped key is visible"
    );
}
