import { checkBuildSkew } from "./skew";
import { showUpdateToast } from "./updateToast";

// Service-worker bootstrap. Ships DARK: `__IH_SW_MODE__` is a build-time
// constant (vite.config.ts `define`) and the default is "off", so in a
// default build the first guard below constant-folds to `return` and the
// minifier strips everything — no registration code reaches the bundle
// (pinned by the SESSION_LOG grep gate and e2e/no-sw-default.spec.ts).
//
// Mode "on": register the precache SW generated by vite-plugin-pwa and wire
// the PROMPT update flow — a newly installed worker WAITS until the user
// clicks Reload in the toast; we then post SKIP_WAITING (handler included in
// the generateSW output) and reload once on controllerchange. An active
// editing session is never yanked onto a new build.
//
// Mode "kill": register the self-destructing sw.js emitted by the eviction
// build (see the EVICTION PROCEDURE block in vite.config.ts).

/** Delay before boot-time toasts/checks: the Toaster mounts inside AppShell,
 *  after React hydration — a toast fired at module-eval time would race it. */
const BOOT_SETTLE_MS = 2500;

/** Re-check sw.js on a timer: long editing sessions never navigate, and the
 *  browser only checks for SW updates on navigation. Without this, the
 *  update prompt could never appear inside a marathon session — the exact
 *  stranded-on-stale-build failure ADR-019's pre-mortem names. */
const UPDATE_POLL_MS = 60 * 60 * 1000;

export function setupServiceWorker(): void {
  if (__IH_SW_MODE__ === "off") return; // default build: statically removed
  if (!("serviceWorker" in navigator)) return;
  if (!import.meta.env.PROD) return; // never in dev (brief: no SW in dev mode)

  window.addEventListener("load", () => {
    if (__IH_SW_MODE__ === "kill") {
      // Belt and suspenders: browsers auto-check the registered sw.js URL on
      // navigation anyway, but an explicit register makes eviction immediate.
      navigator.serviceWorker.register("/sw.js").catch((err: unknown) => {
        console.error("[pwa] kill-mode registration failed", err);
      });
      return;
    }
    void registerPrecacheSw();
  });
}

async function registerPrecacheSw(): Promise<void> {
  // Boot-time skew check, independent of whether registration below succeeds
  // (a stale ALREADY-INSTALLED worker is exactly the case being probed).
  // Delayed so the Toaster is mounted if a banner needs to show.
  window.setTimeout(() => void checkBuildSkew("boot"), BOOT_SETTLE_MS);

  let registration: ServiceWorkerRegistration;
  try {
    registration = await navigator.serviceWorker.register("/sw.js");
  } catch (err) {
    // A failed registration is a plain no-SW session, never a broken app.
    console.error("[pwa] service worker registration failed", err);
    return;
  }

  const promptReload = (worker: ServiceWorker) => {
    showUpdateToast(() => {
      navigator.serviceWorker.addEventListener(
        "controllerchange",
        () => window.location.reload(),
        { once: true },
      );
      worker.postMessage({ type: "SKIP_WAITING" });
    });
  };

  // A user who ignored the prompt last session boots with the new worker
  // already parked in `waiting` — re-offer it (after the Toaster mounts).
  const waiting = registration.waiting;
  if (waiting) {
    window.setTimeout(() => promptReload(waiting), BOOT_SETTLE_MS);
  }

  registration.addEventListener("updatefound", () => {
    const installing = registration.installing;
    if (!installing) return;
    installing.addEventListener("statechange", () => {
      // `installed` + an existing controller = a NEW build is waiting behind
      // the one currently serving this page. (Without a controller it is the
      // very first install — nothing to prompt about.)
      if (
        installing.state === "installed" &&
        navigator.serviceWorker.controller
      ) {
        promptReload(registration.waiting ?? installing);
      }
    });
  });

  window.setInterval(() => {
    registration.update().catch(() => {
      // Offline / transient network failure — the next tick tries again.
    });
  }, UPDATE_POLL_MS);
}
