// ===== FILE: app/src/lib/defaultToolSettings.ts =====
import type { ToolSettings } from "./types";

export const defaultToolSettings: ToolSettings = {
  brushSize: 20,
  hardness: 0.8,
  opacity: 1.0,
  strokeWidth: 3,
  strokeColor: "#ef4444",
  arrowStyle: "single",
  fillMode: "none",
  fillColor: "#3b82f6",
  fillColor2: "#ec4899",
  gradientAngle: 0,
  fillBlock: 16,
  brushColor: "#ef4444",
  brushOpacity: 100,
  paintStabilizer: "off", // off by default
  fontSize: 24,
  fontFamily: "sans-serif",
  fontWeight: "normal",
  textColor: "#000000",
  blurMode: "gaussian",
  blurSize: 32,
  blurIntensity: 8,
  pixelSize: 16,
  redactColor: "#000000",
  effectBrightness: 0,
  effectContrast: 100,
  emoji: "😀",
  emojiSize: 64,
  bgKind: "none",
  bgColor: "#ffffff",
  bgOpacity: 100,
  bgPadding: 8,
  bgCornerRadius: 8,
  bgTail: 135, // degrees — points down-left (the classic speech-bubble default)
  shadowBox: false,
  shadowText: false,
  shadowColor: "#000000",
  shadowOpacity: 60,
  shadowOffsetX: 2,
  shadowOffsetY: 2,
  shadowBlur: 4,
  pinLabel: "numbers",
};
